In [1]:
import numpy as np 

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [6]:
type(myarray)

numpy.ndarray

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape =(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
random = np.random.randint(0,100,10) #0-100 arası rastgele değerlerden 10 elemandan oluşan array
random

array([12, 49, 63, 79, 20, 14, 59, 48, 77, 38])

In [17]:
random.max()

79

In [18]:
random.min()

12

In [19]:
random.argmax() # array'deki en yüksek değerimizin satır sütun bilgisini verir

3

In [20]:
random.argmin() #  array'deki en küçük değerimizin satır sütun bilgisini verir

0

In [ ]:
random.mean() # array'in aritmetik ortalama

45.9

In [23]:
random.shape

(10,)

In [24]:
random.reshape((2,5))

array([[12, 49, 63, 79, 20],
       [14, 59, 48, 77, 38]])

In [26]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat.shape

(10, 10)

In [ ]:
mat[4,5] #4. satır 5. sütundaki değer

45

In [31]:
mat[1:5]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
type(mat)

numpy.ndarray

In [ ]:
mat[: ,1] # 2. sütunun bütün saırlarını alır 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
mat[: ,1].shape

(10,)

In [36]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
mat[1,:].shape

(10,)

In [ ]:
mat[1,:].reshape((10,1))  #2. sütunu 10 ssatır 1 sütun boyutlarına dönüştürüldü

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [39]:
mat[1,:].reshape((10,1)).shape

(10, 1)

In [41]:
mat[0:2,0:2]

array([[ 0,  1],
       [10, 11]])

In [42]:
mat[0:4,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [43]:
mat[0:4,0:4].shape

(4, 4)